services:

  postgres:
    container_name: base_postgres
    image: postgres:15.2
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: base
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
